---
- name: Determine whether to connect as root or admin_user
  local_action: command ansible {{ inventory_hostname }} -m ping -i {{ inventory_file }} -u root
  failed_when: false
  changed_when: false
  register: root_status

- name: Set remote user for each host
  set_fact:
    ansible_ssh_user: "{{ root_status | success | ternary('root', admin_user) }}"

- name: Announce which user was selected
  debug:
    msg: "Note: Ansible will attempt connections as user = {{ ansible_ssh_user }}"
