# Documentation: https://github.com/roots/trellis#wordpress-sites

github_ssh_keys:
  - username: coreybruyere
    authorized:
      - "{{ web_user }}"

project_pre_build_commands_local:
   - path: "{{ project.local_path }}/web/app/themes/coreybruyere"
     cmd: npm install
   - path: "{{ project.local_path }}/web/app/themes/coreybruyere"
     cmd: bower install
   - path: "{{ project.local_path }}/web/app/themes/coreybruyere"
     cmd: gulp --production

project_local_files:
  - name: compiled theme assets
    src: "{{ project.local_path }}/web/app/themes/coreybruyere/dist"
    dest: web/app/themes/coreybruyere


wordpress_sites:
  coreybruyere.com:
    site_hosts:
      - coreybruyere.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@gitlab.com:coreybruyere/coreybruyere.git
    branch: master
    # subtree_path: site # relative path to your Bedrock/WP directory in your repo (above) if it is not the root (like the roots-example-project structure)
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    system_cron: true
    env:
      wp_home: http://coreybruyere.com
      wp_siteurl: http://coreybruyere.com/wp
      wp_env: production
      db_name: example_prod
      db_user: example_dbuser
      db_password: example_dbpassword
      # Generate your keys here: https://api.wordpress.org/secret-key/1.1/salt/
      # These CANNOT contain the characters "{%" in succession
      auth_key: "generateme"
      secure_auth_key: "generateme"
      logged_in_key: "generateme"
      nonce_key: "generateme"
      auth_salt: "generateme"
      secure_auth_salt: "generateme"
      logged_in_salt: "generateme"
      nonce_salt: "generateme"
