---
- include: "{{ deploy_build_before | default('../hooks/example.yml') }}"

- name: Copy project local files
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ deploy_helper.new_release_path }}/{{ item.dest }}"
    group: no
    owner: no
    rsync_opts: --chmod=Du=rwx,--chmod=Dg=rx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=r,--chmod=Fo=r
  with_items: project_local_files

- name: Copy project templates
  template:
    src: "{{ item.src }}"
    dest: "{{ deploy_helper.new_release_path }}/{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: project_templates

- name: Check if project folders exist
  stat:
    path: "{{ deploy_helper.current_path }}/{{ item }}"
  register: project_folder_paths
  with_items: project_copy_folders

- name: Copy project folders
  command: cp -rp {{ deploy_helper.current_path }}/{{ item.item }} {{ deploy_helper.new_release_path }}
  with_items: project_folder_paths.results
  when: item.stat.exists

- include: "{{ deploy_build_after | default('../hooks/example.yml') }}"
